title = "Example of remgo Configuration"
logdir = "/tmp/logs"

[servers]
[servers.Internal]
IPs = ["192.168.125.100", "aldoca.local", "127.0.0.1"]
[servers.External]
IPs = ["192.168.125.200", "192.168.125.60"]
[servers.Mixed]
IPs = ["192.168.125.100", "192.168.125.200", "aldoca.remote"]

[tasks]
[tasks.CheckHostname]
role = "Internal"
command = "hostname"
log = true
sftp = [
# origin, destiny, action(PUT or GET), don't put spaces after commas
"/tmp/file1.txt,/tmp/file1_put.txt,PUT",
"/tmp/file2.txt,/tmp/file2_get.txt,GET"
]

[tasks.CheckDir]
role = "External"
command = "ls -l | tail -3"

[tasks.WhoamIandIP]
user = "root"
role = "Mixed"
command = "whoami; ip addr show"
log = true

[tasks.WhoamIaldo]
user = "aldo"
role = "Mixed"
command = "whoami"
